version: "3.8"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

  mongodb:
    container_name: mongodb
    ports:
      - 27017:27017
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: byteblaze
      MONGO_INITDB_ROOT_PASSWORD: cylane
    restart: on-failure
    networks:
      - mongodb-net
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb

  byteblaze:
    build: .
    image: byteblaze:latest
    container_name: byteblaze
    restart: unless-stopped
    networks:
      - lavalink
      - mongodb-net
    depends_on:
      - lavalink
      - mongodb
    environment:
      - DOCKER_COMPOSE_DATABASE=true
      - DOCKER_COMPOSE_MODE=true
      # Database
      - MONGO_URI=mongodb://byteblaze:cylane@mongodb:27017/streamhatchet?directConnection=true&authSource=admin&replicaSet=replicaset&retryWrites=true
      # Lavalink
      - NODE_URL=lavalink:2333
      - NODE_AUTH=youshallnotpass

networks:
  mongodb-net:
  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink

volumes:
  mongodb_data:
